FROM ubi8/ubi:8.5

MAINTAINER Wiem

ENV PORT 8080

RUN echo 'proxy=http://10.1.10.2:8080' | tee -a /etc/yum.conf && \
    echo 'proxy_username=usrct6dgsm' | tee -a /etc/yum.conf && \
    echo 'proxy_password=cZF$Eyyo' | tee -a /etc/yum.conf && \
    yum install -y httpd && \
    yum clean all

RUN sed -ir -e "/^Listen 80/c\Listen ${PORT}" /etc/httpd/conf/httpd.conf && \
    chown 48:48 -R /etc/httpd/logs/ && \
    chown 48:48  -R /run/httpd/

EXPOSE ${PORT}


COPY ./src/ /var/www/html/

CMD ["httpd", "-D", "FOREGROUND"]
