FROM ubi8/ubi:8.5

MAINTAINER Wiem

LABEL description "custon apache container"

RUN echo 'proxy=http://10.1.10.2:8080' | tee -a /etc/yum.conf && \
    echo 'proxy_username=usrct6dgsm' | tee -a /etc/yum.conf && \
    echo 'proxy_password=cZF$Eyyo' | tee -a /etc/yum.conf && \
    yum install -y httpd && \
    yum clean all

RUN echo "Hello from Containerfile" > /var/www/html/index.html

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]


