apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odf-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-cephfs
